DROP TABLE IF EXISTS MPTT_MODEL;

CREATE TABLE MPTT_MODEL
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	level BIGINT(20) NULL DEFAULT NULL COMMENT '层级',
	lft BIGINT(20) NULL DEFAULT NULL COMMENT '左节点',
	rgt BIGINT(20) NULL DEFAULT NULL COMMENT '右节点',
	parent_id BIGINT(20) NULL DEFAULT NULL COMMENT '父ID',
	node_id VARCHAR(50) NULL DEFAULT NULL COMMENT '森林ID',
	PRIMARY KEY (id)
);